//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisconVT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.DeviceLog = new HashSet<DeviceLog>();
        }
    
        public string IDNO { get; set; }
        public string Plate { get; set; }
        public Nullable<int> DevGroupID { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int UpdateUserID { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual DevGroup DevGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceLog> DeviceLog { get; set; }
        public virtual DeviceRuntime DeviceRuntime { get; set; }
    }
}
